71 generate a markdown brief for the log issue mode
Panduza/panduza-rust-platform pull request #74
Opened 2024-05-28 12:16 UTC by MageTomcatF14

Information can be read in markdown file

2024-05-28 13:49 UTC, XdoctorwhoZ requested changes
Beaucoup de choses à revoir, trop de ligne modifié pour rien.
Attention le point le plus important c'est qu"il faut aller chercher les versions dynamiquement et il ne faut pas les inscrire en brute dans le code.

2024-05-28 13:49 UTC, XdoctorwhoZ commented on Cargo.toml
> -    # "max_level_trace",
must not be modified

2024-05-28 13:49 UTC, XdoctorwhoZ commented on src/connection/connection.rs
> +        // tracing::info!(class="Connection", cname=mqtt_options.client_id(), "Connection created");
must not be removed

2024-05-28 13:49 UTC, XdoctorwhoZ commented on src/connection/task.rs
> +        println!("Connection event loop ended, trying to reconnect");
do not use println here, only logger must be used here

2024-05-28 13:49 UTC, XdoctorwhoZ commented on src/device/device.rs
> +       // println!("Start Interfaces...");
must not be modified

2024-05-28 13:49 UTC, XdoctorwhoZ commented on src/device/factory.rs
> +        // tracing::info!(class="Factory", "List of producers:");
Must not be modified

2024-05-28 13:49 UTC, XdoctorwhoZ commented on src/log/log_issue.rs
> +}
pourquoi tu as cré une fonction vide ?

2024-05-28 13:49 UTC, XdoctorwhoZ commented on src/platform/mod.rs
> +
Le but n'est pas d'inscrire les valeur en brute mais de les collecter dynamique sur le PC de celui qui va executer la platforme

2024-05-28 13:49 UTC, XdoctorwhoZ commented on src/platform/mod.rs
> +        println!("class=Platform, Loading tree file: {:?}", tree_file_path);
Quand la feature log-issue est activé il faut faire println mais quand c'est pas log-issue il faut laisser le tracing

2024-05-29 05:59 UTC, XdoctorwhoZ commented
@MageTomcatF14 merci pour ce premier run

Je vais ajouter plus d'indications:

1. enléve tout ce que tu as fait (tu peux revenir en arriére sur tes commits
2. créer juste une fonction display_issue_body
3. appelle au début du programme cette fonction uniquement si la feature log-issue est activée
4. dans cette fonction tu ajoutes les prints et tout ce qu'il te faut pour afficher les données
5. pour la version de platform, peux-tu regarder si il y a une crate pour lire the cargo.toml

2024-05-29 12:32 UTC, MageTomcatF14 commented
Les modifications sont dans la branche 71-generate-a-markdown-brief-for-the-log-issue-mode_2

2024-05-29 12:45 UTC, closed without merging